### ISSUE TITLE
Not working with Ruby 2.3/Jekyll 3.2.0?

### ISSUE THREAD

**Issue by arclabch** [digitalsparky/jekyll-minifier#10]
On a fresh installation of Ruby 2.3 with Jekyll 3.2.0, jekyll-minifier gives me the following error:

```
jekyll 3.2.0 | Error:  uninitialized class variable @@mtimes in Jekyll::StaticFile
Did you mean? @mtimes mtimes
```

I temporarily worked around the issue by editing line 87 of lib/jekyll-minifier.rb and changing ```@@mtimes``` for ```@mtimes``` but as I don't know ruby, I'm not sure what the implications are. :-)

**Comment by digitalsparky** [comment]
Hi @arclabch I'll check it out and get back to you.
Thanks for contacting me :).

**Comment by sandys** [comment]
+1 - I have the same issue with exactly the same error.

**Comment by digitalsparky** [comment]
It looks like the change occurred here:

https://github.com/jekyll/jekyll/commit/0f74db413110ae7cb435bbd2d7f21a2918dd9cfe

Interestingly, the jekyll api documentation still shows @@mtimes.

**Comment by digitalsparky** [comment]
Fixed in release 0.0.9, pushed to rubygems.

**Comment by sandys** [comment]
works great! thanks.

**Comment by arclabch** [comment]
Great, thank you!
