### ISSUE TITLE
build fails on jekyll 3.1.6

### ISSUE THREAD

**Issue by thierrybgentile** [digitalsparky/jekyll-minifier#11]
Hi! I installed as suggested and I get this when I Jekyll build/serve :
`jekyll 3.1.6 | Error:  undefined method 'mtimes' for Jekyll::StaticFile:Class`

**Comment by digitalsparky** [comment]
Hi,

Thanks for contacting me.

It looks like I made a requirement mistake for your latest version.

The latest version requires 3.2.1 due to upstream api changes.

You could try installing an earlier version of this plug in, or upgrading your jekyll to the latest version.

Hope that helps

Matt

**Comment by mgalibert** [comment]
I have a similar problem with the last version of the gem and jekyll 3.4.3.

`jekyll 3.4.3 | Error:  uninitialized class variable @@mtimes in Jekyll::StaticFile`

Should I use an earlier version of the gem?

Thanks,

Michel
