### ISSUE TITLE
Disable for jekyll-watch

### ISSUE THREAD

**Issue by ygd** [digitalsparky/jekyll-minifier#12]
It would be smoother while developing if you can disable the minifier while `jekyll serve` (jekyll watch) is active. Having an option to activate the minifier for serve like `jekyll serve --minify` would be also cool.

Or only running the minifier by `jekyll build`

**Comment by arpith20** [comment]
You can have multiple configuration files. One with jekyll-minifier disabled for use with `jekyll serve` and other with it enabled for use with `jekyll build`  
With this setup you can do something like this: 
<pre>jekyll serve --config _config_nominify.yml
jekyll build --config _config_minify.yml</pre>

**Comment by kenman345** [comment]
if you use rake you can set up your serve and builds to use different configs or modify the config before serving or building the page.
