### ISSUE TITLE
Generating... jekyll 3.3.0 | Error:  Error: Out of stack space

### ISSUE THREAD

**Issue by linuschowdhary** [digitalsparky/jekyll-minifier#15]
Incremental build: enabled
      Generating...
jekyll 3.3.0 | Error:  Error: Out of stack space

**Comment by linuschowdhary** [comment]
Hi Matt , Getting this issue after command : $jekyll serve 
System OS : Windows 10
Waiting for your valuable response.
Thanks.

**Comment by digitalsparky** [comment]
Hi, I did a quick search and found a similar issue:

http://stackoverflow.com/questions/19234951/rake-assetsprecompile-out-of-stack-space

It unfortunately appears to be a windows issue with ruby/rake.

As much as a pain as it is, it may be best to use a dev vm to compile your code.

Hope that helps.
