### ISSUE TITLE
Please, remove the comments from css files

### ISSUE THREAD

**Issue by ivan-meridianbanc-com** [digitalsparky/jekyll-minifier#19]
Minifier of css files leave comments
`/** * Reset some basic elements */`
`/*!
 * Bootstrap v3.3.5 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */`

**Comment by digitalsparky** [comment]
Hi,

The legal comments are left in by the css minifier, as per the license requirements.
These are identified using /*! and //! comment prefixes (meaning preserve).

The CSS minifier honours these prefixes.

Please read the licenses of your includes before attempting to remove these notices from your sources prior to building.

All other comments are removed.

**Comment by ivan-meridianbanc-com** [comment]
Should this comment be removed ?

`/** * Reset some basic elements */`

**Comment by digitalsparky** [comment]
Yes, they should be, if they're not part of a parent important content block.
Please file a bug on https://github.com/digitalsparky/cssminify/ if you're experiencing these issues.

Thanks :).
