### ISSUE TITLE
Support 3.0 beta?

### ISSUE THREAD

**Issue by x43x61x69** [digitalsparky/jekyll-minifier#2]
Hi,

Seems the plugin was broken in 3.0.0 beta due to dependency settings.

Can you maybe update the gemspec?

Best,
Cai

**Comment by digitalsparky** [comment]
My apologies, thanks for that, I'll do some adjustments and push the change.

**Comment by digitalsparky** [comment]
Gemspec has been update and update has been pushed.

Hope that helps

Matt

**Comment by x43x61x69** [comment]
Hi @digitalsparky !

Thanks for the quick fix.

Unfortunately it's not working with 3.0.0 beta 2 as it seems.

I'll keep using 2.5.3 before 3.0.0 is supported.

Thank you!

**Comment by digitalsparky** [comment]
Tested against jekyll version 3, updated dependencies and pushed pre version to rubygems.
Closing issue.
