### ISSUE TITLE
Remove JS comments

### ISSUE THREAD

**Issue by jp26jp** [digitalsparky/jekyll-minifier#21]
Since JS comments don't get removed, any JS comments made using `//` end up commenting out the rest of the file.

**Comment by digitalsparky** [comment]
Hi, Thanks for your comment, will have a look into this issue and get back to you when I'm able to.

**Comment by digitalsparky** [comment]
Can you expand on where these issues are occurring so I know which library to look at?
jeykll-minifier is essentially a wrapper to 3 different libraries, Uglifier for .js files, cssminify2 for .css files, and htmlcompressor for html and internal html/js/css content, so I need to see where this is actually happening, and potentially raise an issue with the upstream library.

**Comment by jp26jp** [comment]
It's doing this to pure JS files so I guess that would mean uglifier? I had compression of html and css turned off in the settings when I ran into this issue.

**Comment by jp26jp** [comment]
It also only happens if the js file uses the yaml front matter blocks. [Here's an example](https://www.dropbox.com/sh/wbv0xg3e24tehqt/AABbLJFK4ti885o3lCKkOIP5a?dl=1).

**Comment by fermin-silva** [comment]
Same thing for me
```
---
---
// Theme JavaScript

(function($) {
...more things here
```

This results as a one line js which of course does not work

**Comment by rkbhochalya** [comment]
Any update? I'm having same issue.

**Comment by kenman345** [comment]
i'm having this issue too. I have to wrap it in <script> tags but then It has to be inside my include section instead of being able to use relative_include tags and combine all my js files to one so it loads faster.

**Comment by digitalsparky** [comment]
Released
