### ISSUE TITLE
Remove whitespace between HTML tags

### ISSUE THREAD

**Issue by PrimordialHelios** [digitalsparky/jekyll-minifier#25]
Running jekyll-minifier 0.1.1, and after minifying my build looks like this:

    <!doctype html> <html> <head> <meta charset="utf-8"/> <meta name="viewport"...

The spaces in between the tags should be removed, it would cut down a bit on build sizes (especially for larger sites).

**Comment by Birch-san** [comment]
This part of the readme looks relevant:

```yml
jekyll-minifier:
  remove_intertag_spaces: true      # Default: false
```
You'll want to set it to `true`.

I expect the spaces are used to support the HTML feature where _any_ whitespace between tags results in innerText of " ". Whereas if you reduce whitespace to 0: you actually end up with a different document.

**Comment by chris-huxtable** [comment]
This should be possible as of 0.1.2 with the option `remove_spaces_inside_tags`.
