### ISSUE TITLE
Exclusions do not appear to be working

### ISSUE THREAD

**Issue by edelstone** [digitalsparky/jekyll-minifier#26]
I'm not a pro at this stuff, but exclusions of any sort (e.g. `index.html`, `*.html`, `*.css` and others) do not appear to be working in a basic Jekyll 3.5.0 build.

Here is an example of the code I'm putting in `config.yml`

```
jekyll-minifier:
  exclude: '*.css'
```

**Comment by jp26jp** [comment]
Agreed. This started happening to me after Jekyll 3.5 as well.

**Comment by edelstone** [comment]
Looks like there's a PR open about this. #24.

**Comment by digitalsparky** [comment]
#24 has now been merged and a new version published. Apologies for taking so long, moving house is a big task ;).

**Comment by edelstone** [comment]
Thank you and good luck with the move!

**Comment by sonnym** [comment]
I was still having issues with exclude not working (technically, it worked only for the first file encountered), and have opened this pull request:  https://github.com/digitalsparky/jekyll-minifier/pull/27

**Comment by edelstone** [comment]
Good looking out @sonnym. I have t had a chance to check the fix that got pushed.

**Comment by komplexb** [comment]
Can't tell if exclude is working on my Jekyll 3.2.1 installation. 

When I use the snippet below these files still get modified. Is my format correct?
```
jekyll-minifier:
  exclude: ['.htaccess', '.php']
  preserve_php: true
```

**Comment by sonnym** [comment]
Looks like the jekyll version was locked to 3.5 before I wrote the exclusion fix, so the version of jekyll-minifier you are using would be before it was merged:  https://github.com/digitalsparky/jekyll-minifier/blame/master/jekyll-minifier.gemspec#L29

Also, even if your jekyll version were up to date, however, the fix has not been released, so you would need to install from github.

**Comment by angel-carvajal** [comment]
this is still a problem on latest version. can we re-open this?
