### ISSUE TITLE
Is it possible to switch this off during development but on in production automatically?

### ISSUE THREAD

**Issue by Booligoosh** [digitalsparky/jekyll-minifier#30]
Is it possible to switch this off during development but on in production automatically?

**Comment by Convincible** [comment]
Yes please!

**Comment by nfrankel** [comment]
You can have 3 different config files:

* one common
* one for development
* one for production

And set different configurations for development and production, _e.g._:

```
jekyll build --config=_config.yml,_config/_config_prod.yml
```

**Comment by Convincible** [comment]
Aha! - thanks.

**Comment by alexandermeindl** [comment]
It would be nice, if development environments are excluded automatically, like it is supported by https://github.com/penibelst/jekyll-compress-html
With this functionality you have a more easy deployment and only one _config.yml file.
