### ISSUE TITLE
comments are not removed from css

### ISSUE THREAD

**Issue by ssbarnea** [digitalsparky/jekyll-minifier#4]
While clearly it did some kind of minifying, it seems that all the comments are still inside the CSS file. 
Is this normal? Alternatives?

**Comment by digitalsparky** [comment]
There are comments that may be required to remain in source, ie: GPL notifications etc.
CSS and JS minification is done by the YUI Compressor, and as such out of scope for this project.

I will, however, look at replacing the YUI components of this project, as it appears those are no longer maintained.

**Comment by digitalsparky** [comment]
I've found an issue in which HTMLcompressor wasn't removing comments in the HTML, however YUI Compressor is supposed to be doing the removal it's self, without configurations.

At this stage, I needto find a new compressor

**Comment by digitalsparky** [comment]
Switched to Uglifier and CSSminify, added HTML comment removal by default, pushed new version to rubygems.
