### ISSUE TITLE
Have bug since last update 0.1.8

### ISSUE THREAD

**Issue by novus213** [digitalsparky/jekyll-minifier#43]
Hi,
Have this error message since last update
jekyll 3.8.5 | Error:  undefined local variable or method `compressed' for #<Jekyll::StaticFile:0x0000000323d090>
Did you mean?  compress
               compressor
To fix , i have downgrade the call of plugin version for moment.

Edit: i confirm that with the 0.1.6 tag is working again (but not with 0.1.8)

**Comment by MindfulMinun** [comment]
I'm having this same problem. It looks like it has to do with the `compress_javascript` setting. Turning it off gets rid of the issue.

Here's my console output:
```
mindfulminun:benjic.xyz mindfulminun$ JEKYLL_ENV=production bundle exec jekyll build
Ignoring bigdecimal-1.3.4 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.4
Ignoring commonmarker-0.17.9 because its extensions are not built.  Try: gem pristine commonmarker --version 0.17.9
Configuration file: /Users/mindfulminun/Documents/GitHub/benjic.xyz/_config.yml
            Source: /Users/mindfulminun/Documents/GitHub/benjic.xyz
       Destination: /Users/mindfulminun/Documents/GitHub/benjic.xyz/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.8.5 | Error:  undefined local variable or method `compressed' for #<Jekyll::Page @name="H.coffee">
Did you mean?  compress
               compressor
```

I'm on macOS Mojave v10.14.1 running Jekyll 3.8.5 and jekyll-minifier 0.1.8

**Comment by alexmerkel** [comment]
I have the same problem on Debian stretch running jekyll 3.8.5,  jekyll-minifier 0.1.8 and uglifier 4.1.20. 
Using jekyll-minifier 0.1.6 with jekyll 3.8.5 and uglifier 3.2.0 works fine.
