### ISSUE TITLE
Problem with calc() minify

### ISSUE THREAD

**Issue by librisius** [digitalsparky/jekyll-minifier#5]
I have a complicated calc() function in my css. Like this:
calc(100% - (50% - 480px + 250px) )
the problem is, that I get my code without needed space after minifying
calc(100% -(50% - 480px+250px))
and it doesn't work! Please don't minify the spaces near "(" in a calc() function

Fix it as soon as possible

**Comment by digitalsparky** [comment]
The minification is currently performed using the YUI Compressor, as such this is a bug in their code.
This project wraps a series of functions to perform these tasks easily.

As it appears that YUI Compressor is no longer maintained, I will look at replacing the YUI components with a more up to date alternative.

**Comment by alexdelorenzo** [comment]
This is still an issue in mid-2020.
