### ISSUE TITLE
Not minifying HTML in posts?

### ISSUE THREAD

**Issue by bartekpl** [digitalsparky/jekyll-minifier#8]
Unless I did something wrong, the plugin is not minifying HTML in posts. I'm on Jekyll 3.0.2. It seems the same issue is visible at https://digitalsparky.com/ where you have homepage HTML minified, but https://digitalsparky.com/technology/coalition-nbn.html is not. Any hints how to fix it?

**Comment by digitalsparky** [comment]
That may have been due to the change from Post to Document which was just merged.

**Comment by digitalsparky** [comment]
Recent patch seems to have resolved that correctly, give it a go :).
